apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: webapp-wear
  name: webapp-wear-svc
spec:
  ports:
  - port: 8080         #container service port/expose port 
    protocol: TCP      
    targetPort: 8080   #container port 8080
    #targetPort: 80    #container port 80 (if port: 80)
    nodePort: 30080    #manually add/assign nodePort
  selector:
    run: webapp-wear
  type: NodePort
