apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp-wear
  name: webapp-wear
spec:
  containers:
  - image: kodekloud/ecommerce:apparels
    name: webapp-wear
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
